FRENCH translation for the Time to Read extension
senky/phpbb-ext-time-to-read pull request #1
Opened 2018-08-26 18:05 UTC by Galixte

Hi @senky,

could you merge this, please?

2018-08-28 08:17 UTC, senky requested changes

2018-08-28 08:17 UTC, senky commented on language/fr/common.php
> +		1 => '<br>Lu en moyenne 1 minute',
Why did you add `<br>`? Having time to read in a `<div>` ensures it will be displayed on a new line. Please, remove `<br>`s.

2018-09-09 02:00 UTC, Galixte commented
@senky could you test my feedback please?

2018-09-09 11:06 UTC, senky commented
@Galixte what feedback do you mean?

2018-09-11 12:59 UTC, Galixte commented
My feedback about by default the extension doesn't display the “Time to Read” information isn’t displayed on a new line but on the same line than the author and the date.

2018-09-13 09:49 UTC, senky commented
Yes but this is not the correct way to handle this. I will push a fix, but please, only translate exactly what's in English file.

2019-05-28 13:02 UTC, Galixte commented
Hi @senky,

thanks for fixing this.

I updated the FRENCH translation for the Time to Read extension.

Could you merge this, please?

Regards.

2019-05-28 14:05 UTC, merged